version: '3.8'
services:
  postgres:
    image: postgres:13.7
    restart: always
    environment:
      POSTGRES_DB: farm_collector
      POSTGRES_USER: username
      POSTGRES_PASSWORD: verysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  postgres-data:
networks:
  backend: